FROM python:3.10.4-buster

#Upgrade pip as root
RUN pip install --upgrade pip

#Create user to install python package
RUN useradd --create-home worker
USER worker
WORKDIR /home/worker

#Adding PATH for python packages
ENV PATH="/home/worker/.local/bin:${PATH}"

#Copy files to container
#COPY --chown=worker:worker . .
COPY --chown=worker:worker ./marks.py marks.py
COPY --chown=worker:worker ./requirements.txt requirements.txt

#Install packages or dependencies
RUN pip install --user -r requirements.txt

CMD ["python", "marks.py"]
#CMD ["python"]
